Add setavatar command
FlexLabs/modmailbot pull request #28
Opened 2020-10-25 01:49 UTC by sodacova

2020-10-28 23:50 UTC, bsian03 requested changes

2020-10-28 23:50 UTC, bsian03 commented on src/modules/setavatar.js
> +const validate_img = /(http(s?):)([/|.|\w|\s|-])*\.(?:jpg|gif|png)/;
Name should be in UPPER_SNAKE_CASE, also the regex provided allows for invalid URLs to be used (ex. `https://asdasd/asdas.png`). I'd recommend using `/^http(s)?:\/\/[\w.-]+(?:\.[\w.-]+)+[\w\-._~:/?#[\]@!$&'()*+,;=.]+\.(png|jpg|gif|webp)$/` instead

2020-10-28 23:50 UTC, bsian03 commented on src/modules/setavatar.js
> +    bot.registerCommandAlias("setav");
This needs to be after addInboxServerCommand

2020-10-28 23:50 UTC, bsian03 commented on src/modules/setavatar.js
> +        console.log(err);
Please handle errors accordingly instead of just sending them to the console where it'd be hard to debug

2020-10-28 23:50 UTC, bsian03 commented on src/modules/setavatar.js
> +      var newav = `data:${response.headers['content-type']};base64,${response.data.toString('base64')}`;
No `var`s please!!

2020-10-28 23:50 UTC, bsian03 commented on src/modules/setavatar.js
> +        .catch(() => msg.channel.createMessage("<:dynoError:696561633425621078> Couldn\'t change avatar."));
Handle error accordingly here too as well please

2020-10-28 23:54 UTC, bsian03 commented on src/modules/setavatar.js
> +    bot.registerCommandAlias("setav");
Also, you need to specify which alias it belongs to. Refer to Eris docs for information

2020-11-03 01:12 UTC, sodacova commented
Fixed everything in the review, but I'm sure how you wanted errors handled from lines 27-30 though...did you want me to send something to the log channel, instead of sending a "Couldn't change avatar" message in the channel the command is used in?

2020-11-03 18:01 UTC, bsian03 requested changes

2020-11-03 18:01 UTC, bsian03 commented on src/modules/setavatar.js
> +const validate_img = /^http(s)?:\/\/[\w.-]+(?:\.[\w.-]+)+[\w\-._~:/?#[\]@!$&'()*+,;=.]+\.(?:png|jpg|gif|webp)$/;
This still needs to be in UPPER_SNAKE_CASE

2020-11-03 18:01 UTC, bsian03 commented on src/modules/setavatar.js
> +			const response = await axios.get(url, {
If you define `response` as a `let`, moving it outside of the try catch block, and reassign `response` with the axios request inside the try catch block, that would be better. That will also mean that you can move everything else out of the try catch block

2020-11-03 18:01 UTC, bsian03 commented on src/modules/setavatar.js
> +      let newav = `data:${response.headers['content-type']};base64,${response.data.toString('base64')}`;
This isn't reassigned, can be chaned to a `const`

2020-11-03 18:01 UTC, bsian03 commented on src/modules/setavatar.js
> +        new Error(err);
Following on from the try/block, just send a message with the error response

2020-11-03 18:04 UTC, bsian03 commented
Can you also fix the indentation, that would be good

2020-11-03 18:09 UTC, bsian03 requested changes

2020-11-03 18:09 UTC, bsian03 commented on src/modules/setavatar.js
> +    }
Not sure what's going on here

2020-11-03 18:10 UTC, bsian03 commented on src/modules/setavatar.js
> +    }
Yes I do, command alias registration should not happen in the command itself

2020-11-03 18:19 UTC, bsian03 requested changes
Please also lint all files

2020-11-03 18:19 UTC, bsian03 commented on src/modules/setavatar.js
> +    })
Missing semicolon

2020-11-03 18:19 UTC, bsian03 commented on src/modules/setavatar.js
> +      return bot.editSelf({ avatar: newav })
Missing semicolon

2020-11-03 18:19 UTC, bsian03 commented on src/modules/setavatar.js
> +    }
Actually it's not the command alias registration, the command options object is in the wrong place

2020-11-10 22:13 UTC, merged