Add say command and minor fixes
FlexLabs/modmailbot pull request #35
Opened 2021-09-28 00:38 UTC by iiFDCT

Still a wip, will add the rest asap!

2021-11-06 00:36 UTC, iiFDCT commented
May or may not have forgotten about this, but I got time to quickly test everything and get it ready

2021-11-17 01:42 UTC, iiFDCT commented
Nobody merged this so will just use it for the next batch of Dave updates so they all get pushed together :D

2022-02-03 01:02 UTC, beanjo55 requested changes

2022-02-03 01:02 UTC, beanjo55 commented on src/bot.js
> -const bot = new Eris.CommandClient("Bot " + config.token, {
token should always be prefixed with "Bot "

2022-02-03 16:29 UTC, beanjo55 approved these changes

2022-02-03 16:35 UTC, merged